const SAMPLE_MP4 = "https://commondatastorage.googleapis.com/gtv-videos-library/sample/BigBuckBunny.mp4";
const SAMPLE_MP4_2 = "https://commondatastorage.googleapis.com/gtv-videos-library/sample/ElephantsDream.mp4";
const SAMPLE_MP4_3 = "https://commondatastorage.googleapis.com/gtv-videos-library/sample/ForBiggerBlazes.mp4";

export const DUMMY_USERS = [
  {
    id: "u1",
    name: "Creative Minds",
    bio: "Exploring the intersection of art and technology",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=creative",
    subscribers: 125000,
  },
  {
    id: "u2",
    name: "Tech Explorers",
    bio: "Latest in technology and innovation",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tech",
    subscribers: 98000,
  },
  {
    id: "u3",
    name: "Nature Documentary",
    bio: "Bringing nature to your screen",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=nature",
    subscribers: 250000,
  },
  {
    id: "u4",
    name: "Music Studio",
    bio: "Original music and covers",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=music",
    subscribers: 75000,
  },
  {
    id: "u5",
    name: "Learning Hub",
    bio: "Education and personal development",
    avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=learning",
    subscribers: 180000,
  },
];

export const DUMMY_VIDEOS = [
  {
    id: "v1",
    title: "The Future of Web Development in 2025",
    description: "Explore the latest trends and technologies shaping web development. From AI integration to new frameworks, we dive deep into what's next.",
    thumbnail: "https://picsum.photos/320/180?random=1",
    duration: "24:15",
    views: 542000,
    uploadedAt: "2 days ago",
    owner: DUMMY_USERS[0],
    src: SAMPLE_MP4,
    category: "Technology",
  },
  {
    id: "v2",
    title: "Morning Coffee: A Meditative Experience",
    description: "Start your day right with this calming morning routine featuring ambient sounds and beautiful cinematography.",
    thumbnail: "https://picsum.photos/320/180?random=2",
    duration: "12:30",
    views: 127000,
    uploadedAt: "1 week ago",
    owner: DUMMY_USERS[1],
    src: SAMPLE_MP4_2,
    category: "Lifestyle",
  },
  {
    id: "v3",
    title: "Wilderness Survival: Deep in the Forest",
    description: "Join us on an incredible journey through pristine wilderness. Learn survival skills while experiencing untouched nature.",
    thumbnail: "https://picsum.photos/320/180?random=3",
    duration: "45:20",
    views: 2100000,
    uploadedAt: "3 days ago",
    owner: DUMMY_USERS[2],
    src: SAMPLE_MP4_3,
    category: "Nature",
  },
  {
    id: "v4",
    title: "Creating Electronic Music from Scratch",
    description: "A comprehensive guide to music production. Learn the fundamentals and create your first track today.",
    thumbnail: "https://picsum.photos/320/180?random=4",
    duration: "58:45",
    views: 95000,
    uploadedAt: "5 days ago",
    owner: DUMMY_USERS[3],
    src: SAMPLE_MP4,
    category: "Music",
  },
  {
    id: "v5",
    title: "Machine Learning Fundamentals Explained",
    description: "Understand the basics of machine learning without complex mathematics. Perfect for beginners.",
    thumbnail: "https://picsum.photos/320/180?random=5",
    duration: "33:10",
    views: 380000,
    uploadedAt: "1 week ago",
    owner: DUMMY_USERS[4],
    src: SAMPLE_MP4_2,
    category: "Technology",
  },
  {
    id: "v6",
    title: "Urban Photography: Capturing City Life",
    description: "Master the art of street photography with professional tips and techniques.",
    thumbnail: "https://picsum.photos/320/180?random=6",
    duration: "28:55",
    views: 156000,
    uploadedAt: "3 days ago",
    owner: DUMMY_USERS[0],
    src: SAMPLE_MP4_3,
    category: "Arts",
  },
  {
    id: "v7",
    title: "Healthy Meal Prep for the Busy Week",
    description: "Learn how to prepare nutritious meals in under 2 hours for your entire week.",
    thumbnail: "https://picsum.photos/320/180?random=7",
    duration: "19:30",
    views: 89000,
    uploadedAt: "2 days ago",
    owner: DUMMY_USERS[1],
    src: SAMPLE_MP4,
    category: "Lifestyle",
  },
  {
    id: "v8",
    title: "Next.js 16: Building Modern Web Apps",
    description: "Deep dive into Next.js 16 features and how to build scalable applications.",
    thumbnail: "https://picsum.photos/320/180?random=8",
    duration: "41:20",
    views: 267000,
    uploadedAt: "4 days ago",
    owner: DUMMY_USERS[4],
    src: SAMPLE_MP4_2,
    category: "Technology",
  },
  {
    id: "v9",
    title: "Ocean Wonders: Life Below the Surface",
    description: "Discover the mysteries of the deep ocean and its incredible creatures.",
    thumbnail: "https://picsum.photos/320/180?random=9",
    duration: "37:15",
    views: 892000,
    uploadedAt: "1 week ago",
    owner: DUMMY_USERS[2],
    src: SAMPLE_MP4_3,
    category: "Nature",
  },
  {
    id: "v10",
    title: "Jazz Improvisation Masterclass",
    description: "Learn from a jazz legend about the art of improvisation and musical expression.",
    thumbnail: "https://picsum.photos/320/180?random=10",
    duration: "50:40",
    views: 45000,
    uploadedAt: "2 weeks ago",
    owner: DUMMY_USERS[3],
    src: SAMPLE_MP4,
    category: "Music",
  },
  {
    id: "v11",
    title: "Web Design Trends 2025",
    description: "Explore the hottest design trends that are shaping the web this year.",
    thumbnail: "https://picsum.photos/320/180?random=11",
    duration: "22:50",
    views: 412000,
    uploadedAt: "5 days ago",
    owner: DUMMY_USERS[0],
    src: SAMPLE_MP4_2,
    category: "Arts",
  },
  {
    id: "v12",
    title: "Yoga for Stress Relief",
    description: "A 30-minute yoga session designed to reduce stress and improve flexibility.",
    thumbnail: "https://picsum.photos/320/180?random=12",
    duration: "30:00",
    views: 234000,
    uploadedAt: "3 days ago",
    owner: DUMMY_USERS[1],
    src: SAMPLE_MP4_3,
    category: "Lifestyle",
  },
];

export const DUMMY_CATEGORIES = ["All", "Technology", "Nature", "Music", "Lifestyle", "Arts", "Education", "Gaming"];

// Dummy watchlist data
export const DUMMY_WATCHLIST = [
  { videoId: "v1", addedAt: "1 day ago" },
  { videoId: "v5", addedAt: "3 days ago" },
  { videoId: "v8", addedAt: "1 week ago" },
];

// Dummy continue watching data
export const DUMMY_CONTINUE_WATCHING = [
  { videoId: "v1", lastWatchedAt: "1 hour ago", progress: 45 },
  { videoId: "v8", lastWatchedAt: "2 days ago", progress: 75 },
  { videoId: "v3", lastWatchedAt: "3 days ago", progress: 20 },
];

// Dummy comments data
export const DUMMY_COMMENTS = [
  {
    id: "c1",
    userId: "u1",
    userName: "Creative Minds",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=creative",
    content: "Amazing content! Really inspiring.",
    createdAt: "2 hours ago",
    likes: 142,
  },
  {
    id: "c2",
    userId: "u2",
    userName: "Tech Explorer",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tech",
    content: "Very informative. Looking forward to the next video!",
    createdAt: "5 hours ago",
    likes: 87,
  },
  {
    id: "c3",
    userId: "u3",
    userName: "Learning Hub",
    userAvatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=learning",
    content: "Great tutorial. Can you cover advanced topics next?",
    createdAt: "1 day ago",
    likes: 234,
  },
];